In [1]:
import numpy as np

fitness_data = np.array([[5000, 200, 6],[7000, 250, 7],[6500, 230, 6],[8000, 300, 8],[9000, 
320, 7],[7500, 270, 6],[12000, 400, 5]])  

print(fitness_data)

[[ 5000   200     6]
 [ 7000   250     7]
 [ 6500   230     6]
 [ 8000   300     8]
 [ 9000   320     7]
 [ 7500   270     6]
 [12000   400     5]]


In [2]:
print(fitness_data.ndim)
print(fitness_data.shape)
print(fitness_data.size)

2
(7, 3)
21


In [3]:
steps = fitness_data[:, 0]
calories = fitness_data[:, 1]
sleep = fitness_data[:, 2]

print("all value",fitness_data[:,:])
print("All calorie values ",calories)
print("All sleep values ",sleep)
print("First 3 days ",fitness_data[0:4,:])
print("Steps and calories only  ",fitness_data[:,:2])

all value [[ 5000   200     6]
 [ 7000   250     7]
 [ 6500   230     6]
 [ 8000   300     8]
 [ 9000   320     7]
 [ 7500   270     6]
 [12000   400     5]]
All calorie values  [200 250 230 300 320 270 400]
All sleep values  [6 7 6 8 7 6 5]
First 3 days  [[5000  200    6]
 [7000  250    7]
 [6500  230    6]
 [8000  300    8]]
Steps and calories only   [[ 5000   200]
 [ 7000   250]
 [ 6500   230]
 [ 8000   300]
 [ 9000   320]
 [ 7500   270]
 [12000   400]]


In [5]:
print("Steps reshaped into a column (7, 1):",steps.reshape(7,1))
print("Full dataset reshaped into (3, 7):",fitness_data.reshape(3,7))

Steps reshaped into a column (7, 1): [[ 5000]
 [ 7000]
 [ 6500]
 [ 8000]
 [ 9000]
 [ 7500]
 [12000]]
Full dataset reshaped into (3, 7): [[ 5000   200     6  7000   250     7  6500]
 [  230     6  8000   300     8  9000   320]
 [    7  7500   270     6 12000   400     5]]


In [6]:
high_steps_days = fitness_data[fitness_data[:, 0] > 8000]
print("Days where steps > 8000:")
print(high_steps_days)
print("----------------------------------")
low_sleep_days = fitness_data[fitness_data[:, 2] < 6]
print("Days where sleep < 6 hours:")
print(low_sleep_days)
print("----------------------------------")
high_calories_days = fitness_data[fitness_data[:, 1] > 300]
print("Days where calories > 300:")
print(high_calories_days)

Days where steps > 8000:
[[ 9000   320     7]
 [12000   400     5]]
----------------------------------
Days where sleep < 6 hours:
[[12000   400     5]]
----------------------------------
Days where calories > 300:
[[ 9000   320     7]
 [12000   400     5]]


In [7]:
print("Average steps:",  np.mean(steps))
print("Maximum steps:", np.max(steps))
print("Minimum sleep hours:",np.min(sleep))
print("Standard deviation of calories:",  np.std(calories))
print("Range of steps:",  np.max(steps) - np.min(steps))

Average steps: 7857.142857142857
Maximum steps: 12000
Minimum sleep hours: 5
Standard deviation of calories: 61.278887398649196
Range of steps: 7000


* **Patterns:** There is a clear direct relationship where higher step counts lead to more calories burned.


* **Unusual Days:** The 7th (last) day is unusual because it has the highest activity (12,000 steps / 400 calories) but the lowest sleep (only 5 hours).


* **Lessons Learned:** High physical activity came at the expense of rest during that specific day, showing a need for better balance between exercise and sleep.